// mobile/src/components/AppShell.tsx
import type { ReactNode } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { Bell, Search, Settings, Users, Rss } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/stores/auth';

const NAV_ITEMS = [
    { to: '/friends', icon: Users, labelKey: 'side_panel.friends', fallback: 'Friends' },
    { to: '/feed', icon: Rss, labelKey: 'side_panel.feed', fallback: 'Feed' },
    { to: '/notifications', icon: Bell, labelKey: 'side_panel.notifications', fallback: 'Alerts' },
    { to: '/search', icon: Search, labelKey: 'side_panel.search', fallback: 'Search' },
    { to: '/settings', icon: Settings, labelKey: 'view.settings.header', fallback: 'Settings' }
] as const;

export function AppShell({ children }: { children: ReactNode }) {
    const { t } = useTranslation();
    const pathname = useRouterState({ select: (s) => s.location.pathname });
    const currentUser = useAuthStore((s) => s.currentUser);
    const isLoginPage = pathname === '/login';

    if (isLoginPage) {
        return <>{children}</>;
    }

    return (
        <div className="h-dvh overflow-hidden bg-background">
            {/* Header */}
            <header className="fixed inset-x-0 top-0 z-40 flex items-center justify-between px-4 py-3 border-b border-border bg-background"
                style={{ paddingTop: 'calc(0.75rem + env(safe-area-inset-top))' }}>
                <span className="text-sm font-semibold">VRCX Mobile</span>
                {currentUser && (
                    <span className="text-xs text-muted-foreground truncate max-w-[140px]">
                        {currentUser.displayName}
                    </span>
                )}
            </header>

            {/* Content */}
            <main
                className="fixed inset-x-0 overflow-hidden"
                style={{
                    top: 'calc(3rem + env(safe-area-inset-top))',
                    bottom: 'calc(3.75rem + env(safe-area-inset-bottom))'
                }}
            >
                {children}
            </main>

            {/* Bottom Tab Bar */}
            <nav
                className="fixed inset-x-0 bottom-0 z-40 flex border-t border-border bg-background"
                style={{ paddingBottom: 'env(safe-area-inset-bottom)' }}
            >
                {NAV_ITEMS.map(({ to, icon: Icon, labelKey, fallback }) => {
                    const isActive = pathname === to;
                    return (
                        <Link
                            key={to}
                            to={to}
                            className={cn(
                                'flex-1 flex flex-col items-center gap-1 py-2.5 text-xs font-medium transition-colors',
                                isActive ? 'text-primary' : 'text-muted-foreground hover:text-foreground'
                            )}
                        >
                            <Icon className="w-5 h-5" />
                            <span>{t(labelKey, { defaultValue: fallback })}</span>
                        </Link>
                    );
                })}
            </nav>
        </div>
    );
}

// mobile/views/AppShell.vue
<script setup lang="ts">
import { RouterView, useRoute, useRouter } from 'vue-router';
import { computed } from 'vue';

const route = useRoute();
const router = useRouter();

const tabs = [
    { name: 'friends', icon: 'ri-group-line', label: 'Friends' },
    { name: 'feed', icon: 'ri-newspaper-line', label: 'Feed' },
    { name: 'notifications', icon: 'ri-notification-3-line', label: 'Notifications' },
    { name: 'search', icon: 'ri-search-line', label: 'Search' },
    { name: 'settings', icon: 'ri-settings-3-line', label: 'Settings' }
] as const;

const activeTab = computed(() =>
    tabs.find((t) => route.matched.some((m) => m.name === t.name))?.name ?? 'friends'
);

function navigate(name: string) {
    router.push({ name });
}
</script>

<template>
    <div class="flex min-h-dvh flex-col bg-background text-foreground">
        <!-- Main content area (scrollable) -->
        <main class="flex-1 overflow-y-auto pb-[calc(4rem+env(safe-area-inset-bottom))]">
            <RouterView />
        </main>

        <!-- Bottom tab bar -->
        <nav
            class="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-around border-t border-border bg-background/90 backdrop-blur-md"
            :style="{ paddingBottom: 'env(safe-area-inset-bottom)' }"
        >
            <button
                v-for="tab in tabs"
                :key="tab.name"
                class="flex flex-col items-center gap-0.5 px-3 py-2 transition-colors"
                :class="activeTab === tab.name ? 'text-primary' : 'text-muted-foreground'"
                @click="navigate(tab.name)"
            >
                <i :class="[tab.icon, 'text-xl']" />
                <span class="text-[10px] font-medium">{{ tab.label }}</span>
            </button>
        </nav>
    </div>
</template>
